### ISSUE TITLE
Publish to AUR

### ISSUE THREAD

**Issue by jhbruhn** [ros-melodic-arch/ros-melodic-controller-manager#1]
This package has been updated but not published on AUR yet, thus its messages and this package are out of sync. Is this intentional?

**Comment by acxz** [comment]
It may very well be an issue on the automatic syncing side. For the package to be pushed to the AUR, @bionade24 checks the build in a clean chroot. Let's ask him to investigate this further.

**Comment by jhbruhn** [comment]
Turns out publishing this also requires controller_interface to be published due to API changes.

**Comment by acxz** [comment]
I'm afraid you will have to open an issue on the respective packages repo so that we can track which packages need to be synced.

**Comment by bionade24** [comment]
Done. CI currently has issues with the new Protobuf version, so if other package are missing please be patient.
